---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-yaml
            files: .*\.(yaml|yml)$
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint
    - repo: https://github.com/ansible/ansible-lint
      rev: v6.22.0
      hooks:
          - id: ansible-lint
            verbose: true
