---
- name: Install prerequisite packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pre_packages }}"

- name: Add Docker GPG apt key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker Repositories
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
