---
- name: Get current compose version if able
  command: docker-compose --version
  register: dc_version
  changed_when: false
  failed_when: false

- name: Delete docker compose if able
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: dc_version.stdout is defined and docker_compose_version not in dc_version.stdout

- name: Install docker compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
