---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos7
    image: docker.io/geerlingguy/docker-centos7-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos8
    image: docker.io/geerlingguy/docker-centos8-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # Amazon Linux 2 seem to have trouble to start the docker daemon
  # - name: amazonlinux2
  #   image: docker.io/geerlingguy/docker-amazonlinux2-ansible
  #   command: /lib/systemd/systemd
  #   pre_build_image: true
  #   privileged: true
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
