---
name: Molecule
on: [push]
jobs:
    build:
        runs-on: ubuntu-18.04
        strategy:
            max-parallel: 4
            matrix:
                molecule_distro: [centos7, centos8, ubuntu1804, ubuntu1604]

        steps:
            - uses: actions/checkout@v1
              with:
                  path: "${{ github.repository }}"
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.6
            - name: Install dependencies
              run: |
                  sudo apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common openssh-client
                  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                  sudo apt-get update
                  sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
                  python3 -m pip install --upgrade pip
                  python3 -m pip install molecule[docker] yamllint ansible-lint docker
            - name: Test with molecule
              run: |
                  molecule test
              env:
                  MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
                  ROLE_NAME: ansible-role-docker
            - name: Upload to Ansible-Galaxy
              run: |
                  GIT_USER=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
                  GIT_REPO=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 )
                  ansible-galaxy role import --api-key $GALAXY_API_KEY $GIT_USER $GIT_REPO
              env:
                  GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
