---
name: Molecule
on: [push]
jobs:
    molecule:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                molecule_distro: [centos7, centos8, ubuntu1804, ubuntu1604]

        steps:
            - uses: actions/checkout@v1

            - name: Test with molecule
              uses: gofrolist/molecule-action@v2
              env:
                  MOLECULE_DISTRO: ${{ matrix.molecule_distro }}

            - name: Upload to Ansible-Galaxy
              run: |
                  GIT_USER=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
                  GIT_REPO=$(echo $GITHUB_REPOSITORY | cut -d/ -f2 )
                  ansible-galaxy role import --api-key $GALAXY_API_KEY $GIT_USER $GIT_REPO
              env:
                  GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
